name: Create PR from Develop to Main

on:
  # Trigger this workflow when changes are pushed to the 'develop' branch
  push:
    branches:
      - develop

jobs:
  create-pr:
    # Use the latest Ubuntu runner for execution
    runs-on: ubuntu-latest

    steps:
      # Pulls the latest code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        run: |
          gh auth status || gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Pull Request
        # Use GitHub token for authentication
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if an open pull request from 'develop' to 'main' already exists
          if gh pr list --base main --head develop --state open --json number | jq -e '. | length > 0'; then
            echo "PR already exists. Skipping creation."
          else
            # If no PR exists, create a new one
            gh pr create \
              --base main \
              --head develop \
              --title "\`develop\` -> \`main\`" \
              --body "This PR was automatically created via a GitHub Action."
          fi
