name: Create PR from Develop to Main

on:
  push:
    branches:
      - develop

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        run: |
          gh auth status || gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if a PR already exists
          if gh pr list --base main --head develop --state open --json number | jq -e '. | length > 0'; then
            echo "PR already exists. Skipping creation."
          else
            gh pr create \
              --base main \
              --head develop \
              --title "develop -> main" \
              --body "This PR was automatically created via a GitHub Action."
          fi
