name: Create PR from develop to master

on:
  push:
    branches:
      - develop

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
          base: main
          title: 'develop -> main'
          body: 'This PR was automatically created via a GitHub Action.'
          assignees: 'Nilesh2000'
          reviewers: 'Nilesh2000'
